### ISSUE TITLE
Does Binder read the apt.txt automatically?

### ISSUE THREAD

**Issue by kannes** [binder-examples/apt_install#1]
A note like on https://github.com/binder-examples/requirements would be nice, saying if/how Binder will use the apt.txt file. If it really is as easy as including the plain text file, this is super cool and should be said :)

PS: Awesome example btw ;)

**Comment by kannes** [comment]
it does! i will make a PR

**Comment by kannes** [comment]
https://github.com/binder-examples/apt_install/pull/4

**Comment by yuvipanda** [comment]
Merged! Thank you :)
