### ISSUE TITLE
Notebook text is misleading

### ISSUE THREAD

**Issue by kannes** [binder-examples/apt_install#2]
The notebook says 

> This repository installs a fun program via apt. It is runnable from the command line.
> 
> To do so from a notebook, just run the cell below!

Surely that is not when apt is ran? When first reading this, I expected the cell to have a apt invocation but instead it already uses commands that were installed via apt.

**Comment by betatim** [comment]
The text could be clearer. Right now the "To do so from ..." refers to the fact that the tool installed via apt is a command line program and to run that program you would execute `!python ...`

I think it could be clearer by adding a sentence to the first part that clarifies that the installing has happened during the build of the repository and that you are now inside the environment that was built.

**Comment by kannes** [comment]
I will make a PR, unless you beat me to it
