### ISSUE TITLE
How to install man pages?

### ISSUE THREAD

**Issue by davidrpugh** [binder-examples/apt_install#7]
Thanks for all the work that you do! Binder is fantastic.

I would like to install the man pages into the base image. Having the man pages available is very useful for teaching Bash course which is something that I do frequently as a Software Carpentry instructor. 

I can not quite find the right combination of packages to make this work. Currently my `apt.txt` looks as follows.

```
apt-utils
manpages
man-db
```

Any ideas?

**Comment by choldgraf** [comment]
Hmmm, I'm not quite sure, that's a good question. Could you ask this in `discourse.jupyter.org`? That might be a better place for feedback since these template repositories don't get a ton of attention

**Comment by davidrpugh** [comment]
Done!
